export type CheckUnit = "percent" | "multiple" | "count";
export type CheckValue = { value: number | null; percentile: number | null; peerCount: number; gap: string | null };
export type CheckInput = { key: string; field: string; period: string; value: number | null; sourceId: string; label?: string };
export type Source = { id: string; endpoint: string; retrievedAt: string; provider?: string };
export function inputLabel(input: Pick<CheckInput, "key" | "field" | "period">): string;
export function humanPeriod(period: string): string;
export function humanGap(gap: string): string;
export function gapCategory(gap: string | null): "No data" | "Not meaningful" | "Too little history";
export function formatValue(value: number | null, unit: CheckUnit): string;
export function checkCell(result: CheckValue | null | undefined, unit: CheckUnit): { state: "does-not-apply" | "gap" | "measured"; text: string; reason: string | null };
export function formatInput(value: number | null, field?: string, checkUnit?: CheckUnit): string;
export function sourceLine(retrievedAt: string): string;
